### ISSUE TITLE
Error When Mousing Over People

### ISSUE THREAD

**Issue by yajinni** [Eyal-WowHub/TooltipInfo#1]
280x TooltipInfo/Scripts/MythicScore.lua:29: attempt to index local 'color' (a nil value)
[string "@TooltipInfo/Scripts/MythicScore.lua"]:29: in function <TooltipInfo/Scripts/MythicScore.lua:10>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:162: in function <SharedXML/Tooltip/TooltipDataHandler.lua:157>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function <SharedXML/Tooltip/TooltipDataHandler.lua:335>
[string "=[C]"]: in function `ProcessInfo'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:544: in function `SetUnit'
[string "@Grid2/modules/IndicatorTooltip.lua"]:102: in function `GetTooltip'
[string "@Grid2/modules/IndicatorTooltip.lua"]:113: in function `Display'
[string "@Grid2/modules/IndicatorTooltip.lua"]:87: in function `func'
[string "@Grid2/GridFrame.lua"]:103: in function <Grid2/GridFrame.lua:101>

Locals:
tooltip = GameTooltip {
 0 = <userdata>
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:1076
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:1114
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined =[C]:-1
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined =[C]:-1
 SetUnitDebuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetProcessingTooltipInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:488
 AddLineDataText = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:429
 AppendInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:525
 SetSpellBookItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 textLeft1Font = "GameTooltipHeaderText"
 AppendInfoWithSpacer = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:531
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitDebuff = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldLootObject = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetMountBySpellID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTrainerService = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 TextLeft1 = GameTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:505
 IsTooltipType = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:509
 ClearHandlerInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetEnhancedConduit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 StatusBar = GameTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitAura = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitBuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetConduit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetItem = <function> defined @FrameXML/GameTooltip.lua:1110
 SetRecipeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:410
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lu

**Comment by iam3yal** [comment]
@yajinni Should be fixed in the latest version, sorry about the late reply.
